// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNSQ-DbyaXkI7kyTiXLaAyH9KMv1DLmEM',
    appId: '1:472006506070:android:926b4999fd3ab49b0dadf7',
    messagingSenderId: '472006506070',
    projectId: 'chat-7b2fa',
    storageBucket: 'chat-7b2fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMEecF-GT7Pq3uUSJdT7FiLn2d_1pFHaQ',
    appId: '1:472006506070:ios:0c8d1f6aa781e2e90dadf7',
    messagingSenderId: '472006506070',
    projectId: 'chat-7b2fa',
    storageBucket: 'chat-7b2fa.appspot.com',
    androidClientId: '472006506070-rps83hrqoh7jf00fh3f03i4rcl6asf1b.apps.googleusercontent.com',
    iosClientId: '472006506070-sckmpcq3jlr7d8bnk0ovmea8n4nt240b.apps.googleusercontent.com',
    iosBundleId: 'com.example.professionalChat',
  );
}
